package com.comp5590.utils;

/**
 * The StreetUtils class provides utility methods for working with street
 * addresses. It provides methods for generating random street addresses.
 */
public class AddressUtils {

    // All addresses are UK addresses. Generate 100 of each type of address.

    // street numbers, with potential letters (e.g., 11, 45D, 106C)
    private static final String[] STREET_NUMBERS = {
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
        "61",
        "62",
        "63",
        "64",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
        "97",
        "98",
        "99",
        "100",
        "1A",
        "2B",
        "3C",
        "4D",
        "5E",
        "6F",
        "7G",
        "8H",
        "9I",
        "10J",
        "11K",
        "12L",
        "13M",
        "14N",
        "15O",
        "16P",
        "17Q",
        "18R",
        "19S",
        "20T",
        "21U",
        "22V",
        "23W",
        "24X",
        "25Y",
        "26Z",
        "27A",
        "28B",
        "29C",
        "30D",
        "31E",
        "32F",
        "33G",
        "34H",
        "35I",
        "36J",
        "37K",
        "38L",
        "39M",
        "40N",
        "41O",
        "42P",
        "43Q",
        "44R",
        "45S",
        "46T",
        "47U",
        "48V",
        "49W",
        "50X",
        "51Y",
        "52Z",
        "53A",
        "54B",
        "55C",
        "56D",
        "57E",
        "58F",
        "59G",
        "60H",
        "61I",
        "62J",
        "63K",
        "64L",
        "65M",
        "66N",
        "67O",
        "68P",
        "69Q",
        "70R",
        "71S",
        "72T",
        "73U",
        "74V",
        "75W",
        "76X",
        "77Y",
        "78Z",
        "79A",
        "80B",
        "81C",
        "82D",
        "83E",
        "84F",
        "85G",
        "86H",
        "87I",
        "88J",
        "89K",
        "90L",
        "91M",
        "92N",
        "93O",
        "94P",
        "95Q",
        "96R",
        "97S",
        "98T",
        "99U",
        "100V",
    };

    private static final String[] STREET_NAMES = {
        "Main",
        "High",
        "Station",
        "Park",
        "Church",
        "Victoria",
        "Queen",
        "George",
        "Market",
        "Mill",
        "Bridge",
        "West",
        "North",
        "South",
        "East",
        "New",
        "Old",
        "Hill",
        "Green",
        "Grove",
        "Wood",
        "Valley",
        "Water",
        "Creek",
        "Lake",
        "Mount",
        "Holly",
        "Maple",
        "Pine",
        "Cedar",
        "Elm",
        "Oak",
        "Birch",
        "Willow",
        "Spruce",
        "Juniper",
        "Poplar",
        "Chestnut",
        "Walnut",
        "Hazel",
        "Acorn",
        "Apple",
        "Cherry",
        "Peach",
        "Plum",
        "Pear",
        "Orange",
        "Lemon",
        "Lime",
        "Grape",
        "Strawberry",
        "Raspberry",
        "Blueberry",
        "Blackberry",
        "Cranberry",
        "Gooseberry",
        "Currant",
        "Kiwi",
        "Papaya",
        "Mango",
        "Pineapple",
        "Banana",
        "Coconut",
        "Pomegranate",
        "Guava",
        "Passionfruit",
        "Lychee",
        "Durian",
        "Jackfruit",
        "Dragonfruit",
        "Starfruit",
        "Kumquat",
        "Persimmon",
        "Fig",
        "Date",
        "Olive",
        "Avocado",
        "Peach",
        "Plum",
        "Pear",
        "Orange",
        "Lemon",
        "Lime",
        "Grape",
        "Strawberry",
        "Raspberry",
        "Blueberry",
        "Blackberry",
        "Cranberry",
        "Gooseberry",
        "Currant",
        "Kiwi",
        "Papaya",
        "Mango",
        "Pineapple",
        "Banana",
        "Coconut",
        "Pomegranate",
        "Guava",
        "Passionfruit",
        "Lychee",
        "Durian",
        "Jackfruit",
        "Dragonfruit",
        "Starfruit",
        "Kumquat",
        "Persimmon",
        "Fig",
        "Date",
        "Olive",
        "Avocado",
    };

    private static final String[] STREET_TYPES = {
        "Street",
        "Road",
        "Avenue",
        "Lane",
        "Drive",
        "Way",
        "Place",
        "Court",
        "Terrace",
        "Crescent",
        "Close",
        "Square",
        "Mews",
        "Row",
        "Hill",
        "Grove",
        "Park",
        "Gardens",
        "View",
        "Rise",
        "Path",
        "Walk",
        "Green",
        "Meadow",
        "Vale",
        "Dale",
        "Heights",
        "Haven",
        "Crossing",
        "Boulevard",
        "Circle",
        "Loop",
        "Trace",
        "Trail",
        "Run",
        "Pass",
        "Gate",
        "Glen",
        "Ridge",
        "Point",
        "Junction",
        "Plaza",
        "Commons",
        "Harbor",
        "Landing",
        "Port",
        "Wharf",
        "Quay",
        "Pier",
        "Dock",
        "Yard",
        "Court",
        "Alley",
        "Row",
        "Mews",
        "Lane",
        "Way",
        "Place",
        "Terrace",
        "Crescent",
        "Close",
        "Square",
        "Hill",
        "Grove",
        "Park",
        "Gardens",
        "View",
        "Rise",
        "Path",
        "Walk",
        "Green",
        "Meadow",
        "Vale",
        "Dale",
        "Heights",
        "Haven",
        "Crossing",
        "Boulevard",
        "Circle",
        "Loop",
        "Trace",
        "Trail",
        "Run",
        "Pass",
        "Gate",
        "Glen",
        "Ridge",
        "Point",
        "Junction",
        "Plaza",
        "Commons",
        "Harbor",
        "Landing",
        "Port",
        "Wharf",
        "Quay",
        "Pier",
        "Dock",
        "Yard",
    };

    private static final String[] TOWNS = {
        "London",
        "Birmingham",
        "Leeds",
        "Glasgow",
        "Sheffield",
        "Bradford",
        "Liverpool",
        "Edinburgh",
        "Manchester",
        "Bristol",
        "Wakefield",
        "Cardiff",
        "Coventry",
        "Nottingham",
        "Leicester",
        "Sunderland",
        "Belfast",
        "Newcastle",
        "Brighton",
        "Hull",
        "Plymouth",
        "Stoke",
        "Wolverhampton",
        "Derby",
        "Swansea",
        "Southampton",
        "Aberdeen",
        "Portsmouth",
        "York",
        "Peterborough",
        "Dundee",
        "Lancaster",
        "Oxford",
        "Cambridge",
        "Canterbury",
        "Winchester",
        "Chichester",
        "Salisbury",
        "Exeter",
        "Gloucester",
        "Hereford",
        "Worcester",
        "Lichfield",
        "Ripon",
        "Durham",
        "Carlisle",
        "Newcastle",
        "Salford",
        "Wells",
        "Truro",
        "St Albans",
        "Ely",
        "Norwich",
        "Ipswich",
        "Chelmsford",
        "Colchester",
        "Bury",
        "Worcester",
        "Bedford",
        "Luton",
        "Milton Keynes",
        "Northampton",
        "Peterborough",
        "Cambridge",
        "Chelmsford",
        "Ipswich",
        "Norwich",
        "Oxford",
        "Reading",
        "Southampton",
        "Portsmouth",
        "Winchester",
        "Bristol",
        "Bath",
        "Gloucester",
        "Cheltenham",
        "Swindon",
        "Exeter",
        "Plymouth",
        "Truro",
        "Torquay",
        "Plymouth",
        "Bournemouth",
        "Poole",
        "Dorchester",
        "Weymouth",
        "Salisbury",
        "Southampton",
        "Portsmouth",
        "Brighton",
        "Hove",
        "Chichester",
        "Worthing",
        "Eastbourne",
        "Hastings",
        "London",
        "Westminster",
        "Camden",
        "Greenwich",
        "Hackney",
        "Hammersmith",
        "Fulham",
        "Islington",
        "Kensington",
        "Chelsea",
        "Lambeth",
        "Southwark",
        "Tower Hamlets",
        "Wandsworth",
        "Westminster",
        "Barking",
        "Dagenham",
        "Barnet",
        "Bexley",
    };

    private static final String[] COUNTIES = {
        "Greater London",
        "Greater Manchester",
        "West Midlands",
        "West Yorkshire",
        "Lancashire",
        "Nottinghamshire",
        "South Yorkshire",
        "Tyne and Wear",
        "Essex",
        "Merseyside",
        "Hampshire",
        "Kent",
        "Surrey",
        "Hertfordshire",
        "West Sussex",
        "Cheshire",
        "Derbyshire",
        "Oxfordshire",
        "Cambridgeshire",
        "Northamptonshire",
        "Staffordshire",
        "Lincolnshire",
        "Berkshire",
        "Cumbria",
        "Somerset",
        "Leicestershire",
        "Gloucestershire",
        "Norfolk",
        "Suffolk",
        "Wiltshire",
        "Warwickshire",
        "Buckinghamshire",
        "Cornwall",
        "County Durham",
        "Devon",
        "Dorset",
        "East Riding of Yorkshire",
        "East Sussex",
        "Herefordshire",
        "Isle of Wight",
        "North Yorkshire",
        "Northumberland",
        "Shropshire",
        "Bedfordshire",
        "Lancashire",
        "Bristol",
        "Bath",
        "North East Somerset",
        "South Gloucestershire",
        "Plymouth",
        "Torbay",
        "Bournemouth",
        "Poole",
        "Swindon",
        "Wiltshire",
        "Peterborough",
        "Luton",
        "Southend",
        "Thurrock",
        "Medway",
        "Bracknell Forest",
        "West Berkshire",
        "Reading",
        "Slough",
        "Windsor",
        "Maidenhead",
        "Wokingham",
        "Milton Keynes",
        "Brighton",
        "Hove",
        "Portsmouth",
        "Southampton",
        "Isle of Wight",
        "County Durham",
        "Darlington",
        "Hartlepool",
        "Stockton-on-Tees",
        "Redcar",
        "Cleveland",
        "Middlesbrough",
        "Halton",
        "Warrington",
        "Blackburn",
        "Darwen",
        "Blackpool",
        "Kingston upon Hull",
        "East Riding of Yorkshire",
        "North East Lincolnshire",
        "North Lincolnshire",
        "York",
        "Derby",
        "Leicester",
        "Rutland",
        "Nottingham",
        "Herefordshire",
        "Worcestershire",
        "Telford",
        "Wrekin",
        "Stoke-on-Trent",
        "Bath",
        "North East Somerset",
        "South Gloucestershire",
        "Hartlepool",
        "Middlesbrough",
        "Redcar",
        "Cleveland",
        "Stockton-on-Tees",
        "Darlington",
        "Halton",
        "Warrington",
    };

    private static final String[] COUNTRIES = {
        "United Kingdom",
        "United States",
        "Canada",
        "Australia",
        "New Zealand",
        "Ireland",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Portugal",
        "Netherlands",
        "Belgium",
        "Luxembourg",
        "Sweden",
        "Norway",
        "Denmark",
        "Finland",
        "Poland",
        "Czech Republic",
        "Slovakia",
        "Hungary",
        "Romania",
        "Bulgaria",
        "Greece",
        "Turkey",
        "Russia",
        "Ukraine",
        "Belarus",
        "Latvia",
        "Lithuania",
        "Estonia",
        "Kazakhstan",
        "Uzbekistan",
        "Turkmenistan",
        "Tajikistan",
        "Kyrgyzstan",
        "Georgia",
        "Armenia",
        "Azerbaijan",
        "Iran",
        "Iraq",
        "Syria",
        "Lebanon",
        "Jordan",
    };

    // get random 1st street name (address line 1)
    public static String getRandomAddress1() {
        int numberIndex = (int) (Math.random() * STREET_NUMBERS.length);
        int streetIndex = (int) (Math.random() * STREET_NAMES.length);
        int typeIndex = (int) (Math.random() * STREET_TYPES.length);
        return STREET_NUMBERS[numberIndex] + " " + STREET_NAMES[streetIndex] + " " + STREET_TYPES[typeIndex];
    }

    // get random town (address line 2)
    public static String getRandomTown() {
        int index = (int) (Math.random() * TOWNS.length);
        return TOWNS[index];
    }

    // get random county (address line 3)
    public static String getRandomCounty() {
        int index = (int) (Math.random() * COUNTIES.length);
        return COUNTIES[index];
    }

    // get random country
    public static String getRandomCountry() {
        int index = (int) (Math.random() * COUNTRIES.length);
        return COUNTRIES[index];
    }

    // get random postal code (string of letters and numbers), 5 to 8 chars in
    // length (no
    // whitespace)
    public static String getRandomPostalCode() {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < NumberUtils.randomInt(5, 8); i++) {
            int random = (int) (Math.random() * 36);
            if (random < 10) {
                sb.append(random);
            } else {
                sb.append((char) (random + 87));
            }
        }
        return sb.toString();
    }
}
