#!/usr/bin/env bash

# Regex for conventional commits
conventional_commits_regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|spotless)(\(([a-z \-]+)\))?\!?:\ .+$"

# Regex used to exclude message commit that match this regex
exclude=".^"

# Get the commit message (the parameter we're given is just the path to the
# temporary file which holds the message).
commit_message=$(cat "$1")

# Check if the message math the exclude regex, if so, all good baby.
if [[ "$commit_message" =~ $exclude ]]; then
    echo -e 'Commit message meets Conventional Commit standards...'
    exit 0
fi

# Check if message starts with "Merge" if so then return
if [[ "$commit_message" =~ ^Merge ]]; then
    echo -e 'Commit message meets Conventional Commit standards...'
    exit 0
fi

# Check the message, if we match, all good baby.
if [[ "$commit_message" =~ $conventional_commits_regex ]]; then
   echo -e 'Commit message meets Conventional Commit standards...'
   exit 0
fi

# Uh-oh, this is not a conventional commit, show an example and link to the spec.
echo -e 'The commit message does not meet the Conventional Commit standardAn example of a valid message is:\n  feat(login): add the \\x27remember me\\x27 button\nMore details at: https://www.conventionalcommits.org/en/v1.0.0/#summary'
exit 1