#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook. Running Spotless Apply... "
echo "*********************************************************"

# Gather the staged files - to make sure changes are saved only for these files.
stagedFiles=$(git diff --staged --name-only)

# Check that *.java is in the list of staged files
if [[ $stagedFiles != *".java"* ]]; then
  echo "No java files are staged for commit. Exiting pre-commit hook."
  exit 0
fi

# Clean gradle first
./gradlew clean

# run spotless apply
./gradlew check

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    # Add staged file changes to git
    for file in $stagedFiles; do
      if test -f "$file"; then
        git add $file
      fi
    done
    #Exit
    exit 0
else
    echo "*********************************************************"
    echo "       ********************************************      "
    echo 1>&2 "Gradle Check found violations."
    echo "Run ./gradlew spotlessApply in your terminal and fix the issues before trying to commit again."
    echo "       ********************************************      "
    echo "Also check that all tests are passing."
    echo "       ********************************************      "
    echo "Read further up in the logs for more information on why the commit was rejected."
    echo "       ********************************************      "
    echo "*********************************************************"
    #Exit
    exit 1
fi